CREATE TABLE "webhook_deliveries" (
	"id" text PRIMARY KEY NOT NULL,
	"message_id" text NOT NULL,
	"endpoint_id" text NOT NULL,
	"tenant" text,
	"type" text NOT NULL,
	"status" text NOT NULL,
	"attempts" integer NOT NULL,
	"next_attempt_at" timestamp with time zone,
	"last_attempt_at" timestamp with time zone,
	"last_status_code" integer,
	"last_error" text,
	"failure_reason" text,
	"created_at" timestamp with time zone NOT NULL,
	"completed_at" timestamp with time zone,
	"lease_owner" text,
	"lease_until" timestamp with time zone,
	CONSTRAINT "webhook_deliveries_message_endpoint" UNIQUE("message_id","endpoint_id")
);
--> statement-breakpoint
CREATE TABLE "webhook_delivery_attempts" (
	"seq" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "webhook_delivery_attempts_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"delivery_id" text NOT NULL,
	"attempt" integer NOT NULL,
	"at" timestamp with time zone NOT NULL,
	"duration_ms" integer NOT NULL,
	"status_code" integer,
	"response" text,
	"error" text
);
--> statement-breakpoint
CREATE TABLE "webhook_endpoints" (
	"id" text PRIMARY KEY NOT NULL,
	"tenant" text,
	"url" text NOT NULL,
	"event_types" text[] NOT NULL,
	"description" text,
	"enabled" boolean NOT NULL,
	"disabled_reason" text,
	"failing_since" timestamp with time zone,
	"secrets" jsonb NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "webhook_messages" (
	"id" text PRIMARY KEY NOT NULL,
	"type" text NOT NULL,
	"tenant" text,
	"body" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "webhook_deliveries" ADD CONSTRAINT "webhook_deliveries_message_id_webhook_messages_id_fk" FOREIGN KEY ("message_id") REFERENCES "public"."webhook_messages"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "webhook_delivery_attempts" ADD CONSTRAINT "webhook_delivery_attempts_delivery_id_webhook_deliveries_id_fk" FOREIGN KEY ("delivery_id") REFERENCES "public"."webhook_deliveries"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "webhook_deliveries_due" ON "webhook_deliveries" USING btree ("next_attempt_at") WHERE "webhook_deliveries"."status" = 'pending';--> statement-breakpoint
CREATE INDEX "webhook_deliveries_endpoint_created_at" ON "webhook_deliveries" USING btree ("endpoint_id","created_at");--> statement-breakpoint
CREATE INDEX "webhook_deliveries_tenant_created_at" ON "webhook_deliveries" USING btree ("tenant","created_at");--> statement-breakpoint
CREATE INDEX "webhook_deliveries_completed_at" ON "webhook_deliveries" USING btree ("completed_at");--> statement-breakpoint
CREATE INDEX "webhook_delivery_attempts_delivery" ON "webhook_delivery_attempts" USING btree ("delivery_id","at");--> statement-breakpoint
CREATE INDEX "webhook_endpoints_tenant_created_at" ON "webhook_endpoints" USING btree ("tenant","created_at");